server:
  port: 9000

spring:
  datasource:
    username: cris
    url: jdbc:mysql://localhost:3306/company
    password:
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password: Redis#2023!
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,env,beans,metrics
#  health:
#    circuitbreakers:
#      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 8
      minimumNumberOfCalls: 4
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 2
      registerHealthIndicator: true

